#!/bin/sh

dir=${AB_JOLOKIA_DIR:-/opt/jolokia}
sep="="

if [ -z ${AB_JOLOKIA_OFF+x} ]; then
   opts="-javaagent:$dir/jolokia.jar"
   config=${AB_JOLOKIA_CONFIG:-$dir/jolokia.properties}
   if [ -f "$config" ]; then
      # Configuration takes precedence
      opts="${opts}${sep}${config}"
      sep=","
      grep -q -e '^host' ${config} && host_in_config=1
   fi
   if [ -z ${AB_JOLOKIA_HOST+x} ] && [ -z ${host_in_config+x} ]; then
      AB_JOLOKIA_HOST='0.0.0.0'
   fi
   if [ -n "$AB_JOLOKIA_HOST" ]; then
      opts="${opts}${sep}host=${AB_JOLOKIA_HOST}"
      sep=","
   fi
   if [ -n "$AB_JOLOKIA_PORT" ]; then
      opts="${opts}${sep}port=${AB_JOLOKIA_PORT}"
      sep=","
   fi
   if [ -n "$AB_JOLOKIA_USER" ]; then
      opts="${opts}${sep}user=${AB_JOLOKIA_USER}"
      sep=","
   fi
   if [ -n "$AB_JOLOKIA_PASSWORD" ]; then
      opts="${opts}${sep}password=${AB_JOLOKIA_PASSWORD}"
      sep=","
   fi
   # Integration with OpenShift client cert auth
   if [ -n "$AB_JOLOKIA_AUTH_OPENSHIFT" ]; then
      ca_cert="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      if [ -n "${AB_JOLOKIA_CA_CERT}" ]; then
         ca_cert="${AB_JOLOKIA_CA_CERT}"
      fi
      principal="cn=OpenShift API Proxy"   # TODO: Set this to a sensible default value
      if [  x"${AB_JOLOKIA_AUTH_OPENSHIFT}" != x"${AB_JOLOKIA_AUTH_OPENSHIFT/=/}" ]; then
         # Supposed to contain a principal name to check
         principal="${AB_JOLOKIA_AUTH_OPENSHIFT}"
      fi
      auth_opts="protocol=https,useSslClientAuthentication=true,extraClientCheck=true,caCert=${ca_cert},clientPrincipal=${principal}"
      jolokia_opts="${jolokia_opts}${jsep}${auth_opts}"
      jsep=","
   fi
   # Add extra opts to the end
   if [ -n "$AB_JOLOKIA_OPTS" ]; then
      opts="${opts}${sep}${AB_JOLOKIA_OPTS}"
      sep=","
   fi
   if [ "x$sep" != 'x=' ] ; then
     echo ${opts}
   fi
fi
