#!/bin/sh
dir=${AB_DIR:-/opt/agent-bond}
sep="="
# Options separators defined to avoid clash with fish-pepper templating
_AB_OPEN="{""{"
_AB_CLOSE="}""}"
if [ -z ${AB_OFF+x} ]; then
   opts="-javaagent:$dir/agent-bond.jar"
   config=${AB_CONFIG:-$dir/agent-bond.properties}
   if [ -f "$AB_CONFIG" ]; then
      # Configuration takes precedence
      opts="${opts}${sep}${AB_CONFIG}"
      sep=","
   fi
   if [ -z ${AB_ENABLED+x} ] || [ x${AB_ENABLED} != x${AB_ENABLED/jolokia/} ]; then
     # Direct options only if no configuration is found
     jsep=""
     jolokia_opts=""
     if [ -n "${AB_JOLOKIA_CONFIG}" ] && [ -f "${AB_JOLOKIA_CONFIG}" ]; then
        jolokia_opts="${jolokia_opts}${jsep}config=${AB_JOLOKIA_CONFIG}"
        jsep=","
        grep -q -e '^host' ${AB_JOLOKIA_CONFIG} && host_in_config=1
     fi
     if [ -z ${AB_JOLOKIA_HOST+x} ] && [ -z ${host_in_config+x} ]; then
        AB_JOLOKIA_HOST='0.0.0.0'
     fi
     if [ -n "$AB_JOLOKIA_HOST" ]; then
        jolokia_opts="${jolokia_opts}${jsep}host=${AB_JOLOKIA_HOST}"
        jsep=","
     fi
     if [ -n "$AB_JOLOKIA_PORT" ]; then
        jolokia_opts="${jolokia_opts}${jsep}port=${AB_JOLOKIA_PORT}"
        jsep=","
     fi
     if [ -n "$AB_JOLOKIA_USER" ]; then
        jolokia_opt="${jolokia_opts}${jsep}user=${AB_JOLOKIA_USER}"
        jsep=","
     fi
     if [ -n "$AB_JOLOKIA_PASSWORD" ]; then
        jolokia_opts="${jolokia_opts}${jsep}password=${AB_JOLOKIA_PASSWORD}"
        jsep=","
     fi
     # Integration of 3rd party environments
     if [ -n "$AB_JOLOKIA_AUTH_OPENSHIFT" ]; then
        jolokia_opts="${jolokia_opts}${jsep}authMode=delegate,authUrl=${AB_JOLOKIA_AUTH_OPENSHIFT%/}/users/~,authPrincipalSpec=json:metadata/user,authIgnoreCerts=true"
        jsep=","
     fi
      # Add extra opts to the end
     if [ -n "$AB_JOLOKIA_OPTS" ]; then
        jolokia_opts="${jolokia_opts}${jsep}${AB_JOLOKIA_OPTS}"
        jsep=","
     fi
     opts="${opts}${sep}jolokia${_AB_OPEN}${jolokia_opts}${_AB_CLOSE}"
     sep=","
   fi
   if [ -z ${AB_ENABLED+x} ] || [ x${AB_ENABLED} != x${AB_ENABLED/jmx_exporter/} ]; then
     je_opts=""
     jsep=""
     if [ -n "$AB_JMX_EXPORTER_OPTS" ]; then
        opts="${opts}${sep}jmx_exporter${_AB_OPEN}${AB_JMX_EXPORTER_OPTS}${_AB_CLOSE}"
        sep=","
     else
        port=${AB_JMX_EXPORTER_PORT-9779}
        config=${AB_JMX_EXPORTER_CONFIG-/opt/agent-bond/jmx_exporter_config.json}
        opts="${opts}${sep}jmx_exporter${_AB_OPEN}${port}:${config}${_AB_CLOSE}"
        sep=","
     fi
   fi
   if [ "x$sep" != 'x=' ] ; then
     echo ${opts}
   fi
fi
